In [1]:
# day2 of 30days-of-Jupyter
# Today we will see the use of slicing operator in Numpy 1-D aaray 
# Addition, substraction and product of vectors

In [2]:
import numpy as np


In [3]:
arr1 = np.array([10,15,20,30])


In [4]:
arr1[0:4]

# slicing operator for index o to 4

array([10, 15, 20, 30])

In [5]:
arr1[0:]



array([10, 15, 20, 30])

In [6]:
arr1[:4]

array([10, 15, 20, 30])

In [7]:
arr1[:]

array([10, 15, 20, 30])

In [8]:
arr1[0::2]

array([10, 20])

In [9]:
arr1[::]

array([10, 15, 20, 30])

In [10]:
arr1[2:4]

array([20, 30])

In [11]:
#

In [12]:
# Two new numpy 1-D array for vector addition , substaraction and product
u = np.array([11,12])
v = np.array([10,15])


In [13]:
z = u+v

# z stores addition of u and v

In [14]:
z

array([21, 27])

In [15]:
z1 = u-v

# z1 stores substraction u and v 

In [16]:
z1

array([ 1, -3])

In [39]:
# Data type of new z and z1 is also a new numpy 1-D array
type(z)

numpy.ndarray