In [2]:
# day2 of 30days-of-Jupyter
# Today we will see the use of slicing operator in Numpy 1-D aaray 
# Addition, substraction and product of vectors

In [3]:
import numpy as np


In [4]:
arr1 = np.array([10,15,20,30])


In [5]:
arr1[0:4]

# slicing operator for index o to 4

array([10, 15, 20, 30])

In [6]:
arr1[0:]



array([10, 15, 20, 30])

In [7]:
arr1[:4]

array([10, 15, 20, 30])

In [8]:
arr1[:]

array([10, 15, 20, 30])

In [9]:
arr1[0::2]

array([10, 20])

In [10]:
arr1[::]

array([10, 15, 20, 30])

In [11]:
arr1[2:4]

array([20, 30])

In [12]:
#

In [13]:
# Two new numpy 1-D array for vector addition , substaraction and product
u = np.array([11,12])
v = np.array([10,15])


In [22]:
z = u+v
z
# z stores addition of u and v

array([21, 27])

In [23]:
z1 = u-v
z1
# z1 stores substraction u and v 

array([ 1, -3])

In [24]:
# Data type of new z and z1 is also a new numpy 1-D array
type(z1)

numpy.ndarray

In [19]:
# Dot product of two vector in form of NUmpy 1-D array
# = [a/b] . [c/d]
# = a*c + b*d

In [28]:
z3 = np.dot(u,v)
z3

290

In [29]:
# Adding a constant value to an Numpy 1-D array
# z4 = u+1
# if we add scaler value to numpy array so it will add that value to each element
# This property known as broadcasting

In [31]:
z4 = u+10
z4

array([21, 22])

In [32]:
# Universal functions in Numpy are simple mathematical functions.
# It is just a term that we gave to mathematical functions in the Numpy library. 
# Numpy provides various universal functions that cover a wide variety of operations.

In [36]:
arr4 = np.array([10,20,40,50])
# we have new 1-D numpy array as arr4 let's apply some amazing universal / mathematical functions of numpy.

In [39]:
# mean function to find out average value of numpy array
mean_arr4 = arr4.mean()
mean_arr4

30.0